### PR TITLE
Memory Leak Fixes

### LINKED ISSUE #27: Potential LGAR-C memory leak detected by Valgrind
Using Valgrind package, it shows possible memory leak in this code. Details are described in the attached file.
[Lgar_mem_leak.txt](https://docs.google.com/document/d/1nNhSUhSi9716eoIBRNfqjCp_zgLzydgntsu-To6pHeo/edit). It may potentially affect running ngen successfully using the submodule.

## Current behavior
Here is a summary of detected memory leak (more details in the attachment):
```. 
==32209== LEAK SUMMARY:
==32209==    definitely lost: 11,947,888 bytes in 278,819 blocks
==32209==    indirectly lost: 14,943,168 bytes in 233,445 blocks
==32209==      possibly lost: 13,920 bytes in 218 blocks
==32209==    still reachable: 3,176 bytes in 56 blocks
==32209==         suppressed: 0 bytes in 0 blocks
```

## Expected behavior

Expected the numbers in the above list to be 0.

## Steps to replicate behavior (include URLs)

In the build step, using:
`cmake ../ -DCMAKE_BUILD_TYPE=Debug -DSTANDALONE=ON`

In the run step, using the following command:
`valgrind --leak-check=full ./build/lasam_standalone configs/config_lasam_Bushland.txt`
or other config input files.

See the attachment for more options.

### PR DESCRIPTION
**Pull request by hellkite500**
**_Serious memory leaks exist_** in this implementation, as noted in #27.  Running through the llvm address-sanitizer with leak detection, the total memory leaked by the bmi test using

```sh
lasam_standalone ./configs/config_lasam_Bushland.txt
```

is nearly 30 MB!

```sh
SUMMARY: AddressSanitizer: 26907277 byte(s) leaked in 512522 allocation(s).
```

This happens predominantly because the linked list data structure supporting the layered wetting fronts dynamically allocates list elements using malloc, but these are never freed/deleted.  These lists are then copied using `listCopy`, between each time step to track previous state and current state, but once copied, the old memory is inaccessible and "leaks".  This is extremely problematic when used in the NextGen model engine (ngen) since we potentially initialize over 800k models, and then run each for a period of time ranging from hours to decades!  These memory leaks at that scale quickly exhaust system resources (as evident by the 10 day CONUS tests where #27 was first identified!).

Back of the envelop math implies this could leak up to **_*24 TB!!!!*_** of memory in only a year long simulation (the length of time of the simulation used in the test above)!

This PR address the bulk of the memory leaks, especially those occurring in the BMI implementation.  With these changes, the memory leaks are now minimal and seem to be related mostly to the use of `fprintf` and `scanf` and shouldn't be leaking memory for every simulation time step!

```sh
SUMMARY: AddressSanitizer: 949 byte(s) leaked in 11 allocation(s).
```

Care should be taken in future developments and work with this customized linked list to ensure that dynamic memory allocations are properly freed.  This PR also shows where other model states and temporaries have dynamic memory allocation and had no corresponding cleanup code.  Particularly with dynamic allocation in loops (such as in Update which had nested loops in a function intended to be called in a loop) dynamic memory use must be handled correctly.

## Additions

- listDelete in linked_list.cxx
- bmi Finalize implemenation
- destructor for BMI class

## Changes

- Ensure dynamic memory allocations are deleted before the pointers are lost

## Testing

1. Ran the standalone code with address sanitizer to confirm fixed memory leaks

## Notes

- For some weird reason, running the standalone test with this PR code produces the output twice, but the values are the same and consistent with the output variables run from master before these changes are applied.

## Todos

- Noted a couple other odd things in comments in the code for anyone curious.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [x] Linux
- [x] MacOS

Merging this PR closes #27.

### CODE REVIEW

**Comment by stcui007** [comment]
I put the full report here for convenience:
```
 valgrind --leak-check=full ./build/lasam_standalone configs/config_lasam_Phillipsburg.txt
==110617== Memcheck, a memory error detector
==110617== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==110617== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==110617== Command: ./build/lasam_standalone configs/config_lasam_Phillipsburg.txt
==110617==
==110617== Conditional jump or move depends on uninitialised value(s)
==110617==    at 0x5E2E852: __ieee754_pow_sse2 (e_pow.c:75)
==110617==    by 0x5E403EB: pow (w_pow.c:27)
==110617==    by 0x4172E0: calc_theta_from_h(double, double, double, double, double, double) (soil_funcs.cxx:149)
==110617==    by 0x41530B: lgar_read_vG_param_file(char const*, int, double, soil_properties_*) (lgar.cxx:2299)
==110617==    by 0x40EC95: InitFromConfigFile(std::string, model_state*) (lgar.cxx:542)
==110617==    by 0x40C935: lgar_initialize(std::string, model_state*) (lgar.cxx:77)
==110617==    by 0x40748C: BmiLGAR::Initialize(std::string) (bmi_lgar.cxx:39)
==110617==    by 0x4038B6: main (bmi_main_lgar.cxx:50)
==110617==
==110617== Conditional jump or move depends on uninitialised value(s)
==110617==    at 0x5E2E88A: __ieee754_pow_sse2 (e_pow.c:86)
==110617==    by 0x5E403EB: pow (w_pow.c:27)
==110617==    by 0x4172E0: calc_theta_from_h(double, double, double, double, double, double) (soil_funcs.cxx:149)
==110617==    by 0x41530B: lgar_read_vG_param_file(char const*, int, double, soil_properties_*) (lgar.cxx:2299)
==110617==    by 0x40EC95: InitFromConfigFile(std::string, model_state*) (lgar.cxx:542)
==110617==    by 0x40C935: lgar_initialize(std::string, model_state*) (lgar.cxx:77)
==110617==    by 0x40748C: BmiLGAR::Initialize(std::string) (bmi_lgar.cxx:39)
==110617==    by 0x4038B6: main (bmi_main_lgar.cxx:50)
==110617==
==110617== Conditional jump or move depends on uninitialised value(s)
==110617==    at 0x5E2E8B0: __ieee754_pow_sse2 (e_pow.c:95)
==110617==    by 0x5E403EB: pow (w_pow.c:27)
==110617==    by 0x4172E0: calc_theta_from_h(double, double, double, double, double, double) (soil_funcs.cxx:149)
==110617==    by 0x41530B: lgar_read_vG_param_file(char const*, int, double, soil_properties_*) (lgar.cxx:2299)
==110617==    by 0x40EC95: InitFromConfigFile(std::string, model_state*) (lgar.cxx:542)
==110617==    by 0x40C935: lgar_initialize(std::string, model_state*) (lgar.cxx:77)
==110617==    by 0x40748C: BmiLGAR::Initialize(std::string) (bmi_lgar.cxx:39)
==110617==    by 0x4038B6: main (bmi_main_lgar.cxx:50)
==110617==
==110617== Conditional jump or move depends on uninitialised value(s)
==110617==    at 0x5E2E8C7: __ieee754_pow_sse2 (e_pow.c:95)
==110617==    by 0x5E403EB: pow (w_pow.c:27)
==110617==    by 0x4172E0: calc_theta_from_h(double, double, double, double, double, double) (soil_funcs.cxx:149)
==110617==    by 0x41530B: lgar_read_vG_param_file(char const*, int, double, soil_properties_*) (lgar.cxx:2299)
==110617==    by 0x40EC95: InitFromConfigFile(std::string, model_state*) (lgar.cxx:542)
==110617==    by 0x40C935: lgar_initialize(std::string, model_state*) (lgar.cxx:77)
==110617==    by 0x40748C: BmiLGAR::Initialize(std::string) (bmi_lgar.cxx:39)
==110617==    by 0x4038B6: main (bmi_main_lgar.cxx:50)
==110617==
==110617== Conditional jump or move depends on uninitialised value(s)
==110617==    at 0x5E2ED91: __ieee754_pow_sse2 (e_pow.c:96)
==110617==    by 0x5E403EB: pow (w_pow.c:27)
==110617==    by 0x4172E0: calc_theta_from_h(double, double, double, double, double, double) (soil_funcs.cxx:149)
==110617==    by 0x41530B: lgar_read_vG_param_file(char const*, int, double, soil_properties_*) (lgar.cxx:2299)
==110617==    by 0x40EC95: InitFromConfigFile(std::string, model_state*) (lgar.cxx:542)
==110617==    by 0x40C935: lgar_initialize(std::string, model_state*) (lgar.cxx:77)
==110617==    by 0x40748C: BmiLGAR::Initialize(std::string) (bmi_lgar.cxx:39)
==110617==    by 0x4038B6: main (bmi_main_lgar.cxx:50)
==110617==

*********************************************************
-------------------- Simulation Summary -----------------
------------------------ Mass balance -------------------
Initial water in soil     =  45.1158503556 cm
Total precipitation       =  99.0854000000 cm
Total infiltration        =  88.8044496039 cm
Final water in soil       =  45.6315405858 cm
Surface ponded water      =   0.0000000000 cm
Surface runoff            =  10.2809503961 cm
GIUH runoff               =  10.2809503961 cm
Total percolation         =   0.0000000000 cm
Total AET                 =  88.2887593432 cm
Total PET                 = 147.9532940266 cm
Total discharge (Q)       =  10.2809503961 cm
Vol change (calibration)  =   0.0000000000 cm
Global balance            =   3.057077e-08 cm

*********************************************************
-------------------- Simulation Summary -----------------
------------------------ Mass balance -------------------
Initial water in soil     =  45.1158503556 cm
Total precipitation       =  99.0854000000 cm
Total infiltration        =  88.8044496039 cm
Final water in soil       =  45.6315405858 cm
Surface ponded water      =   0.0000000000 cm
Surface runoff            =  10.2809503961 cm
GIUH runoff               =  10.2809503961 cm
Total percolation         =   0.0000000000 cm
Total AET                 =  88.2887593432 cm
Total PET                 = 147.9532940266 cm
Total discharge (Q)       =  10.2809503961 cm
Vol change (calibration)  =   0.0000000000 cm
Global balance            =   3.057077e-08 cm
Time                      =   80.11 sec
==110617==
==110617== HEAP SUMMARY:
==110617==     in use at exit: 6,703,968 bytes in 279,283 blocks
==110617==   total heap usage: 797,221 allocs, 517,938 frees, 39,024,780 bytes allocated
==110617==
==110617== 24 bytes in 1 blocks are possibly lost in loss record 12 of 35
==110617==    at 0x4C29EC3: malloc (vg_replace_malloc.c:309)
==110617==    by 0x411BC6: lgar_move_wetting_fronts(double, double*, int, double, int, double*, double*, int*, double*, wetting_front**, wetting_front*, soil_properties_*) (lgar.cxx:1226)
==110617==    by 0x408932: BmiLGAR::Update() (bmi_lgar.cxx:357)
==110617==    by 0x403F9D: main (bmi_main_lgar.cxx:129)
==110617==
==110617== 24 bytes in 1 blocks are possibly lost in loss record 13 of 35
==110617==    at 0x4C29EC3: malloc (vg_replace_malloc.c:309)
==110617==    by 0x411BE4: lgar_move_wetting_fronts(double, double*, int, double, int, double*, double*, int*, double*, wetting_front**, wetting_front*, soil_properties_*) (lgar.cxx:1227)
==110617==    by 0x408932: BmiLGAR::Update() (bmi_lgar.cxx:357)
==110617==    by 0x403F9D: main (bmi_main_lgar.cxx:129)
==110617==
==110617== 5,736 bytes in 239 blocks are definitely lost in loss record 32 of 35
==110617==    at 0x4C29EC3: malloc (vg_replace_malloc.c:309)
==110617==    by 0x411BC6: lgar_move_wetting_fronts(double, double*, int, double, int, double*, double*, int*, double*, wetting_front**, wetting_front*, soil_properties_*) (lgar.cxx:1226)
==110617==    by 0x4083EA: BmiLGAR::Update() (bmi_lgar.cxx:268)
==110617==    by 0x403F9D: main (bmi_main_lgar.cxx:129)
==110617==
==110617== 5,736 bytes in 239 blocks are definitely lost in loss record 33 of 35
==110617==    at 0x4C29EC3: malloc (vg_replace_malloc.c:309)
==110617==    by 0x411BE4: lgar_move_wetting_fronts(double, double*, int, double, int, double*, double*, int*, double*, wetting_front**, wetting_front*, soil_properties_*) (lgar.cxx:1227)
==110617==    by 0x4083EA: BmiLGAR::Update() (bmi_lgar.cxx:268)
==110617==    by 0x403F9D: main (bmi_main_lgar.cxx:129)
==110617==
==110617== 3,344,688 bytes in 139,362 blocks are definitely lost in loss record 34 of 35
==110617==    at 0x4C29EC3: malloc (vg_replace_malloc.c:309)
==110617==    by 0x411BC6: lgar_move_wetting_fronts(double, double*, int, double, int, double*, double*, int*, double*, wetting_front**, wetting_front*, soil_properties_*) (lgar.cxx:1226)
==110617==    by 0x408932: BmiLGAR::Update() (bmi_lgar.cxx:357)
==110617==    by 0x403F9D: main (bmi_main_lgar.cxx:129)
==110617==
==110617== 3,345,216 bytes in 139,384 blocks are definitely lost in loss record 35 of 35
==110617==    at 0x4C29EC3: malloc (vg_replace_malloc.c:309)
==110617==    by 0x411BE4: lgar_move_wetting_fronts(double, double*, int, double, int, double*, double*, int*, double*, wetting_front**, wetting_front*, soil_properties_*) (lgar.cxx:1227)
==110617==    by 0x408932: BmiLGAR::Update() (bmi_lgar.cxx:357)
==110617==    by 0x403F9D: main (bmi_main_lgar.cxx:129)
==110617==
==110617== LEAK SUMMARY:
==110617==    definitely lost: 6,701,376 bytes in 279,224 blocks
==110617==    indirectly lost: 0 bytes in 0 blocks
==110617==      possibly lost: 48 bytes in 2 blocks
==110617==    still reachable: 2,544 bytes in 57 blocks
==110617==         suppressed: 0 bytes in 0 blocks
==110617== Reachable blocks (those to which a pointer was found) are not shown.
==110617== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==110617==
==110617== For counts of detected and suppressed errors, rerun with: -v
==110617== Use --track-origins=yes to see where uninitialised values come from
==110617== ERROR SUMMARY: 96 errors from 11 contexts (suppressed: 0 from 0)
```

**Comment by hellkite500** [comment]
@stcui007 That config triggered a slightly different code path which had some temporary allocations that weren't free'd correctly.  I ran the config and was able to fix up that leak as well in [e652bb2](https://github.com/NOAA-OWP/LGAR-C/pull/28/commits/e652bb2582e391adee7e4147a2de6c674c664fc3).

**Comment by stcui007** [comment]
Good work!

File: src/linked_list.cxx
Comment (donaldwj) [inline src/linked_list.cxx:1]: We should probably just make the current api map to internal use of std::list.

File: src/bmi_lgar.cxx [hunk 1]
```diff
@@ -17,6 +17,14 @@
 // default verbosity is set to 'none' other option 'high' or 'low' needs to be specified in the config file
 string verbosity="none";
 
+/**
+ * @brief Delete dynamic arrays allocated in Initialize() and held by this object
+ * 
+ */
+BmiLGAR::~BmiLGAR(){
+  if( giuh_ordinates != nullptr ) delete [] giuh_ordinates;
+  if( giuh_runoff_queue != nullptr ) delete [] giuh_runoff_queue;
```
Comment (PhilMiller) [inline src/bmi_lgar.cxx:26]: C++ nitpick: `delete nullptr` is safe, there's no need to manually check.
```suggestion
  delete [] giuh_ordinates;
  delete [] giuh_runoff_queue;
```

File: src/bmi_lgar.cxx [hunk 2]
```diff
@@ -48,6 +56,20 @@ Initialize (std::string config_file)
...
+ */
+void BmiLGAR::realloc_soil(){
+  if(state->lgar_bmi_params.soil_depth_wetting_fronts != nullptr)
+    delete [] state->lgar_bmi_params.soil_depth_wetting_fronts;
+  if(state->lgar_bmi_params.soil_moisture_wetting_fronts != nullptr)
+    delete [] state->lgar_bmi_params.soil_moisture_wetting_fronts;
+
+  state->lgar_bmi_params.soil_depth_wetting_fronts = new double[state->lgar_bmi_params.num_wetting_fronts];
+  state->lgar_bmi_params.soil_moisture_wetting_fronts = new double[state->lgar_bmi_params.num_wetting_fronts];
+}
```
Comment (PhilMiller) [inline src/bmi_lgar.cxx:71]: As written, it seems like these could easily become `std::vector` and avoid the need for manual memory management.

File: src/bmi_lgar.cxx (hunk 1 above)
Comment (PhilMiller) [reply src/bmi_lgar.cxx:26]: This applies all the way down the PR

File: src/lgar.cxx [hunk 3]
```diff
@@ -1134,7 +1137,9 @@ extern void lgar_move_wetting_fronts(double timestep_h, double *volin_cm, int wf
       double theta_new = lgar_theta_mass_balance(layer_num, soil_num, psi_cm, new_mass, prior_mass, AET_demand_cm,
 						 delta_thetas, delta_thickness, soil_type, soil_properties);
       actual_ET_demand = *AET_demand_cm;
-      
+      //done with delta_thetas and delta_thickness, cleanup memory
+      free(delta_thetas);
+      free(delta_thickness);
```
Comment (PhilMiller) [inline src/lgar.cxx:1142]: Rather than adding `free` calls, just change the pointer variables to `std::vector<double>`, and pass down `delta_thetas.data()` for the one function argument.

File: src/linked_list.cxx [hunk 4]
```diff
@@ -26,6 +26,20 @@
...
+/* the dynamic memory used in creating and manipultating the */
+/* list. (added by NJF)                                                     */
+/*###########################################################*/
+extern void listDelete(struct wetting_front* head)
+{
+  if( head != NULL ){
+    struct wetting_front *next = head->next;
+    free( head );
+    listDelete(next);
+  }
```
Comment (PhilMiller) [inline src/linked_list.cxx:41]: Sadly, C++ does not guarantee tail call optimization, so we don't want to risk blowing up the stack
```suggestion
  while (head != NULL) {
    struct wetting_front *next = head->next;
    free( head );
    head = next;
  }
```

File: src/main.cxx [hunk 5]
```diff
@@ -435,6 +435,7 @@ for(time_step_num=0;time_step_num<num_time_steps;time_step_num++)
       printf(" ************ time step %d ******** \n",time_step_num);
     }
     
+    if( state_previous != NULL ) listDelete(state_previous);
     state_previous = NULL;
     state_previous = listCopy(head);
```
Comment (PhilMiller) [inline src/main.cxx:440]: The condition is redundant with the implementation of `listDelete`, and the repeat assignment is pointless.
```suggestion
    listDelete(state_previous);
    state_previous = listCopy(head);
```

File: src/bmi_main_lgar.cxx [hunk 6]
```diff
@@ -155,13 +155,15 @@ int main(int argc, char *argv[])
...
       fprintf(outlayer_fptr,"# Timestep = %d, %s \n", i, time[i].c_str());
       write_state(outlayer_fptr, model_state.get_model()->head);
+      delete [] soil_moisture_wetting_front;
+      delete [] soil_thickness_wetting_front;
     }
 
   }
 
   // do final mass balance
   model_state.global_mass_balance();
```
Comment (peterlafollette) [inline src/bmi_main_lgar.cxx:165]: I suggest removing this line, as global_mass_balance is called in Finalize now.

**Review by peterlafollette — COMMENTED** [review]
Awesome work everyone! Great that the memory leak issues have been so thoroughly identified / addressed. In future developments, we'll make sure we free dynamically allocated memory. 

I've tested the changed code in standalone and in ngen, running multiple catchments from the same realization, and for the most part things seem to be good. The one change I would suggest is removing global_mass_balance from bmi_main_lgar.cxx because it is also called in Finalize (see my comment), so the simulation results are currently printed twice (at least in standalone mode). Please also note that there has been an accepted PR since this one, so I think rebasing might be necessary. Aside from these minor things, this looks great.

**Comment by stcui007** [comment]
This reminds me a similar thing. It seems that in lgar.cxx, it prints our
"Mass balance" info every time step. For multi-processing jobs it does this
for every process. This becomes an issue for large scale processing, on
CONUS, for example, not only slows down the computation but also write out
a big file if you use nohup. Just wonder if this part can be optionally
made inactive when running in the framework.

**Comment by peterlafollette** [comment]
I'm wondering, what is the verbosity set to in the lgar configs you're
using? The options are:

verbosity=none
verbosity=low
verbosity=high

and if verbosity is set to none then there should only be printing when the
model completes (and not for every time step). The verbosity is set to none
in the Phillipsburg and Bushland examples in the configs folder.

**Comment by stcui007** [comment]
The verbosity is set to none. The config was generated for me by Ahmad. One
example is as follows.

verbosity=none
soil_params_file=inputsNL/lasam/vG_default_params.dat
layer_thickness=200.0[cm]
initial_psi=2000.0[cm]
timestep=300[sec]
endtime=1000[hr]
forcing_resolution=3600[sec]
ponded_depth_max=0[cm]
use_closed_form_G=false
layer_soil_type=4
wilting_point_psi=15495.0[cm]
field_capacity_psi=340.9[cm]

If what you said is true, I should take another look before saying too
much. But I am pretty sure when I commented out these print statements, the
output file becomes much smaller.

File: src/bmi_lgar.cxx (hunk 2 above)
Comment (hellkite500) [reply src/bmi_lgar.cxx:71]: Agreed in principle, in practice, this would require modifying [lgar.cxx](https://github.com/NOAA-OWP/LGAR-C/blob/01dc874996c4fcaa748a43b49d5a8cb041698a96/src/lgar.cxx#L83) which is essentially extern `C` code masquerading as c++ code.

It is not clear if this project is intended to support the core lgar in C style code and provide a C++ BMI wrapper, or if it is intended to implement all of lgar in c++.  This needs to be a larger discussion outside the scope of fixing these memory leaks.

File: src/linked_list.cxx (hunk 4 above)
Comment (hellkite500) [reply src/linked_list.cxx]: If the wetting front list is large enough to blow up the stack on a recursive walk, then we probably need to consider a different data structure for the wetting fronts anyways...but either way, I added this suggestion...

File: src/main.cxx (hunk 5 above)
Comment (hellkite500) [reply src/main.cxx:440]: I left that to be as "close as possible to the original code", but it really isn't a significant difference so may as well simplify.

**Comment by hellkite500** [comment]
> This reminds me a similar thing. It seems that in lgar.cxx, it prints our "Mass balance" info every time step. For multi-processing jobs it does this for every process. This becomes an issue for large scale processing, on CONUS, for example, not only slows down the computation but also write out a big file if you use nohup. Just wonder if this part can be optionally made inactive when running in the framework.

This should be tracked in a separate issue.

File: src/bmi_main_lgar.cxx (hunk 6 above)
Comment (hellkite500) [reply src/bmi_main_lgar.cxx]: removed in [3fab3e8](https://github.com/NOAA-OWP/LGAR-C/pull/28/commits/3fab3e8c58cfd0c329fbaf1ce504c5a3c21d9d17)

File: src/linked_list.cxx
Comment (hellkite500) [reply src/linked_list.cxx:1]: Definitely worth consideration, but is a large scope to discuss outside this PR (see other related comments about C/C++ mixing in lgar-c)

File: src/bmi_lgar.cxx (hunk 1 above)
Comment (hellkite500) [reply src/bmi_lgar.cxx]: addressed in [d52d6f0](https://github.com/NOAA-OWP/LGAR-C/pull/28/commits/d52d6f0dd041b4c5d90004a3ff8285cfc28afd6c)

**Review by peterlafollette — APPROVED** [review]
Again great work all. I've tested the updated code in ngen mode (running 1 or multiple catchments from one realization file) and in standalone mode, and the results are all as expected. From my perspective, the branch can be merged to master.
