### PR TITLE
fix: seek to beginning of config file after looking for verbose key

### LINKED ISSUE #32: Seek to beginning of config file after looking for `verbose` key
https://github.com/NOAA-OWP/LGAR-C/blob/567adc75bea3ed3580427592f198638b0a8a32ef/src/lgar.cxx#L184-L206

If `verbose` is not the first key in the config file, `lgar` will likely not correctly interpret a configuration file. This is because the code looks for the `verbose` key in all lines of the config and never seeks back to the beginning of the file before parsing the config file for parameters.

### PR DESCRIPTION
**Pull request by aaraney**
fixes #32

See #32 for more information.

### CODE REVIEW

File: src/lgar.cxx [hunk 1]
```diff
@@ -205,6 +205,8 @@ extern void InitFromConfigFile(string config_file, struct model_state *state)
     }
   }
 
+  // seek to beginning of input after searching for 'verbosity'
+  fp.seekg(0, fp.beg);
```
Comment (hellkite500) [inline src/lgar.cxx:209]: probably a good idea to call `clear()` here to reset any potential error flags on the stream before continuing.  C++ 11 will clear the `eofbit` in `seekg` (older c++ standards do not,  however), and there could potentially be other error flags set from processing the stream, so if the intent is to "start over", clear expressly resets all error flags. Also, `seekg(0, fp.beg)` is equivalent to `seekg(0)`.

```suggestion
  fp.clear();
  fp.seekg(0, fp.beg);
```

**Review by hellkite500 — CHANGES_REQUESTED** [review]

File: src/lgar.cxx (hunk 1 above)
Comment (aaraney) [reply src/lgar.cxx:210]: Sweet! I had the same question! Great catch. Just merged it in. Let squash and merge this

**Review by hellkite500 — APPROVED** [review]

**Comment by aaraney** [comment]
:tada: thanks, @hellkite500!
